"""add_shifts_and_user_preferences

Revision ID: 3347dc470bab
Revises: 21f1972b7201
Create Date: 2025-12-05 12:46:31.994956

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3347dc470bab"
down_revision: Union[str, Sequence[str], None] = "21f1972b7201"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pto_categories", sa.Column("accrued_ytd", sa.Float(), nullable=True))
    op.create_index(
        op.f("ix_pto_categories_name"), "pto_categories", ["name"], unique=False
    )
    op.add_column("users", sa.Column("shift_length", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("shifts_per_week", sa.Integer(), nullable=True))
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("users", "shifts_per_week")
    op.drop_column("users", "shift_length")
    op.drop_index(op.f("ix_pto_categories_name"), table_name="pto_categories")
    op.drop_column("pto_categories", "accrued_ytd")
    # ### end Alembic commands ###
