"""add series_id to shifts

Revision ID: 7106bfd9af3f
Revises: 3347dc470bab
Create Date: 2025-12-05 15:31:54.435002

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7106bfd9af3f"
down_revision: Union[str, Sequence[str], None] = "3347dc470bab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shifts", sa.Column("series_id", sa.String(), nullable=True))
    op.create_index(op.f("ix_shifts_series_id"), "shifts", ["series_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shifts_series_id"), table_name="shifts")
    op.drop_column("shifts", "series_id")
    # ### end Alembic commands ###
